package.json

- alteração versão package.json 1.4.1

Release 1.4.1

---

src/resources/Contrato.ts
src/resources/interface/ISimetraRequest.ts
src/resources/interface/ISimetraResponse.ts
src/simetra-sdk.ts

Release 1.5.0

---

src/resources/Cliente.ts
src/resources/interface/ISimetraRequest.ts
src/resources/interface/ISimetraResponse.ts

* Cliente.consultaCadastroVindi

Release - 1.6.0

---

package.json

Release - 1.6.1

---

package.json
src/resources/Atendimento.ts
src/resources/interface/ISimetraRequest.ts
src/resources/interface/ISimetraResponse.ts

Release - 1.7.0

---

dist/types/resources/HabilitacaoProvisoria.d.ts
src/resources/HabilitacaoProvisoria.ts
src/resources/interface/ISimetraRequest.ts
src/resources/interface/ISimetraResponse.ts

https://midiasimples.monday.com/boards/880921956/pulses/903454090

Trocar api de habilitação provisória

---

package.json
src/resources/Contrato.ts
src/resources/interface/ISimetraRequest.ts
src/resources/interface/ISimetraResponse.ts

- https://github.com/midia-simples/simetra-sdk/commit/a5e5132111fa0f4c04f7168c3ad33d9bdac5a413
- Não houve alterações de código

Release - 1.8.5

---

src/resources/Contrato.ts
src/resources/interface/ISimetraRequest.ts
src/resources/interface/ISimetraResponse.ts

- Alterar dia de vencimento do contrato, alterar nome e senha wifi #49

Release - 1.9.0

---

package.json

- https://github.com/midia-simples/simetra-sdk/commit/185f4e138a45af84f3111f7dd8f1e978fd8d39fd

Release - 1.9.1

---

package.json
src/resources/Contrato.ts
src/resources/interface/ISimetraResponse.ts

- Função para buscar dias de vencimento validos #52

Release - 1.9.2

---

package.json
src/resources/Cliente.ts
src/resources/interface/ISimetraRequest.ts
src/resources/interface/ISimetraResponse.ts

- Feature/cadastrar cartao novo e cartao pagamento rapido (#57)

Release - 1.10.0

---

package.json
src/resources/Cliente.ts
src/resources/interface/ISimetraRequest.ts
src/resources/interface/ISimetraResponse.ts

Release - 1.11.0

---

package.json
src/resources/Cliente.ts
src/resources/interface/ISimetraRequest.ts
src/resources/interface/ISimetraResponse.ts

- Consulta de cartão do cliente (nova rota) (#64)

Release - 1.12.0

---

package.json
src/resources/Cliente.ts
src/resources/interface/ISimetraRequest.ts
src/resources/interface/ISimetraResponse.ts

Release - 1.14.0

---

package.json
src/resources/Atendimento.ts
src/resources/interface/ISimetraRequest.ts
src/resources/interface/ISimetraResponse.ts

- Interação do usuário pelo App Americanet nos chamados (#74)

Release - 1.15.0

---

package.json
src/resources/Atendimento.ts
src/resources/Cliente.ts
src/resources/Contrato.ts
src/resources/HabilitacaoProvisoria.ts
src/resources/IncidenteRede.ts
src/resources/Produto.ts
src/resources/Resource.ts
src/resources/SimetraError.ts
src/resources/Titulo.ts
src/resources/Vencimentos.ts

- Request e data no SimetraError (#80)

Release - 1.17.1

---

package.json
src/resources/Cliente.ts
src/resources/interface/ISimetraRequest.ts

- Passando código de contrato no envio de SMS (#84)

Release - 1.17.2

---

package.json
src/resources/Contrato.ts
src/resources/interface/ISimetraRequest.ts
src/resources/interface/ISimetraResponse.ts

- feat: Integrando endpoint de gerar boleto para contratos PIX (#86)

Release - 1.18.0

---

package.json
src/resources/Contrato.ts
src/resources/interface/ISimetraRequest.ts
src/resources/interface/ISimetraResponse.ts

- feat: Alterar forma de pagamento grupo (universal) (#88)

Release - 1.19.0

---

dist/types/resources/Debito.d.ts
package.json
src/resources/Debito.ts
src/resources/interface/ISimetraRequest.ts
src/resources/interface/ISimetraResponse.ts
src/simetra-sdk.ts

- feat: debito cadastrar conta
- feat: debito consultar conta
- build: update 1.21.0

feat: consulta e cadastro de contas bancárias

---

package.json
src/resources/Resource.ts
yarn.lock

- Feat/credenciais body (#102)

Release - 1.22.1
